# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=15)),
                ('review', models.CharField(max_length=15)),
                ('rating', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='first_app.User')),
            ],
        ),
    ]
