# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170729_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user_of_book',
        ),
        migrations.AddField(
            model_name='books',
            name='user_of_book',
            field=models.ManyToManyField(related_name='books', to='first_app.User'),
        ),
    ]
