# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170730_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_of_book',
            field=models.ManyToManyField(related_name='book_user', to='first_app.User'),
        ),
    ]
