# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20170730_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_of_book',
            field=models.ManyToManyField(related_name='book_user', to='first_app.User'),
        ),
    ]
