# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20170730_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_of_book',
            field=models.ManyToManyField(to='first_app.User'),
        ),
    ]
